import { CarouselItemType } from "../src/components/carouselcard/carouselitem";

export const Carousel_1: CarouselItemType[] = [
  {
    image: "outlet/1.jpeg",
    rating: 0,
    name: 'Dell Inspiron 16 Plus i7620-7592GRE-PUS / i7-12700H / 40GB RAM / 1TB SSD / 16" 3K (3072 x 1920) / Intel Irix Xe Graphics / Win 11 Home - Open Box',
    reviews: 0,
    saveAmount: "800",
    price: "999.99",
    isMarketplace: true,
  },
  {
    image: "outlet/2.jpeg",
    rating: 0,
    name: 'Dell Latitude 9420 2in1, 14" QHD Touch, Intel IRIS XE, i7-1185G7, 16GB RAM, 512GB SSD, WIN 11 PRO -Certified Refurbished',
    reviews: 0,
    saveAmount: "1,801",
    price: "899.00",
    isMarketplace: true,
  },
  {
    image: "outlet/3.jpeg",
    rating: 0,
    name: 'Apple iPad Pro 12.9" (6th Gen) Apple M2 Chip / 256GB / Wi-Fi / Space Gray - Open Box',
    reviews: 0,
    saveAmount: "50",
    price: "1,299.99",
    isMarketplace: true,
  },
  {
    image: "outlet/4.jpeg",
    rating: 4.5,
    name: "Refurbished (Excellent) - Samsung Galaxy S21 5G 128GB - Phantom Grey - Unlocked - Certified Refurbished",
    reviews: 2,
    saveAmount: "387",
    price: "332.94",
    isMarketplace: true,
  },
  {
    image: "outlet/5.jpg",
    rating: 2,
    name: 'Open Box - Samsung 65" 4K UHD HDR LED Tizen Smart TV (UN65TU7000FXZC) - Titan Grey',
    reviews: 6,
    price: "679.99",
    isMarketplace: false,
    ehf: "7.50",
  },
  {
    image: "outlet/6.jpg",
    rating: 4,
    name: 'Acer 23.8" FHD 165Hz 1ms GTG VA LED Gaming Monitor (QG241Y PBMIIPX) - Black - Only at Best Buy',
    reviews: 21,
    price: "249.97",
    isMarketplace: false,
    ehf: "3.00",
  },
  {
    image: "outlet/7.jpg",
    rating: 2,
    name: 'Open Box - Samsung 70" 4K UHD HDR LED Tizen OS Smart TV (UN70TU6985FXZC) - 2020',
    reviews: 3,
    saveAmount: "70",
    price: "629.99",
    isMarketplace: false,
    ehf: "7.50",
  },
  {
    image: "outlet/8.jpeg",
    rating: 0,
    name: 'Samsung SP-LSP9TFAXZC The Premiere 130" 4K Smart Triple RGB Laser Projector - Open Box - 10/10 Condition',
    reviews: 0,
    saveAmount: "2,702",
    price: "3,298.00",
    isMarketplace: true,
  },
  {
    image: "outlet/9.jpeg",
    rating: 0,
    name: "Samsung Q-Series Premium Soundbar HW-Q990/ZC- [Canada Version] (2023) - Open Box - 10/10 Condition",
    reviews: 0,
    saveAmount: "848",
    price: "1,449.99",
    isMarketplace: true,
  },
  {
    image: "outlet/10.jpeg",
    rating: 3,
    name: "Open Box - Apple AirPods (3rd Generation) In-Ear Truly Wireless Headphones with MagSafe Charging Case - White",
    reviews: 18,
    saveAmount: "45",
    price: "154.99",
    isMarketplace: true,
  },
  {
    image: "outlet/11.jpeg",
    rating: 0,
    name: "Refurbished (Excellent) - Dyson Official Outlet - Airwrap Styler Complete Long - Blue/Copper - (1 Year Dyson Warranty)",
    reviews: 0,
    saveAmount: "150",
    price: "469.99",
    isMarketplace: true,
  },
  {
    image: "outlet/12.jpeg",
    rating: 3.5,
    name: "Refurbished (Good) - Segway Ninebot Electric Kick Scooter MAX G30LP",
    reviews: 14,
    saveAmount: "490",
    price: "559.99",
    isMarketplace: true,
  },
  {
    image: "outlet/13.png",
    rating: 3.5,
    name: "Refurbished (Good) - RBSM Sports Mud Adder Electric bike 500 watts 48 volt, LCD display",
    reviews: 21,
    saveAmount: "999",
    price: "999.99",
    isMarketplace: true,
  },
  {
    image: "outlet/14.jpg",
    rating: 2,
    name: "Canon PowerShot ELPH 360 HS WiFi 20.2MP 12x Optical Zoom Digital Camera - Black - Open Box",
    reviews: 3,
    price: "199.99",
    isMarketplace: false,
    ehf: "0.70",
  },
];
